double numberA = new Random().Next(1, 10);
double numberB = new Random().Next(1, 10);
Console.WriteLine("Первое число - " + numberA);
Console.WriteLine("Второе число - " + numberB);
double resultSum = numberA + numberB;
double resultDiv = numberA / numberB;
Console.Write("Сумма чисел ");
Console.WriteLine(resultSum);
Console.Write("Частное чисел ");
Console.WriteLine(resultDiv);